"""create domain tables

Revision ID: 20260817_0001
Revises:
Create Date: 2026-08-18 10:22:04.216610
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260817_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("material_code", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("specification", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(description) <> ''", name="ck_materials_description"),
        sa.CheckConstraint(
            "btrim(material_code) <> ''", name="ck_materials_material_code"
        ),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_materials_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_materials_source_system_non_blank"
        ),
        sa.CheckConstraint(
            "specification IS NULL OR btrim(specification) <> ''",
            name="ck_materials_specification",
        ),
        sa.CheckConstraint(
            "unit IS NULL OR btrim(unit) <> ''", name="ck_materials_unit"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_materials_source_identity"
        ),
    )
    op.create_table(
        "ships",
        sa.Column("ship_code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=True),
        sa.Column("vessel_type", sa.Text(), nullable=True),
        sa.Column("planned_delivery_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(ship_code) <> ''", name="ck_ships_ship_code"),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_ships_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_ships_source_system_non_blank"
        ),
        sa.CheckConstraint(
            "customer_name IS NULL OR btrim(customer_name) <> ''",
            name="ck_ships_customer_name",
        ),
        sa.CheckConstraint("name IS NULL OR btrim(name) <> ''", name="ck_ships_name"),
        sa.CheckConstraint(
            "vessel_type IS NULL OR btrim(vessel_type) <> ''",
            name="ck_ships_vessel_type",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ship_code", name="uq_ships_ship_code"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_ships_source_identity"
        ),
    )
    op.create_table(
        "suppliers",
        sa.Column("supplier_code", sa.Text(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "btrim(canonical_name) <> ''", name="ck_suppliers_canonical_name"
        ),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_suppliers_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_suppliers_source_system_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(supplier_code) <> ''", name="ck_suppliers_supplier_code"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_suppliers_source_identity"
        ),
    )
    op.create_table(
        "project_tasks",
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("task_code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_end", sa.Date(), nullable=True),
        sa.Column("actual_start", sa.Date(), nullable=True),
        sa.Column("actual_end", sa.Date(), nullable=True),
        sa.Column("planned_progress", sa.Numeric(), nullable=True),
        sa.Column("actual_progress", sa.Numeric(), nullable=True),
        sa.Column("critical_path", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(name) <> ''", name="ck_project_tasks_name"),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_project_tasks_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''",
            name="ck_project_tasks_source_system_non_blank",
        ),
        sa.CheckConstraint("btrim(task_code) <> ''", name="ck_project_tasks_task_code"),
        sa.CheckConstraint(
            "actual_progress IS NULL OR "
            "(actual_progress >= 0 AND actual_progress <= 1)",
            name="ck_project_tasks_actual_progress",
        ),
        sa.CheckConstraint(
            "actual_start IS NULL OR actual_end IS NULL OR actual_start <= actual_end",
            name="ck_project_tasks_actual_dates",
        ),
        sa.CheckConstraint(
            "planned_progress IS NULL OR "
            "(planned_progress >= 0 AND planned_progress <= 1)",
            name="ck_project_tasks_planned_progress",
        ),
        sa.CheckConstraint(
            "planned_start IS NULL OR planned_end IS NULL "
            "OR planned_start <= planned_end",
            name="ck_project_tasks_planned_dates",
        ),
        sa.ForeignKeyConstraint(
            ["ship_id"], ["ships.id"], name="fk_project_tasks_ship_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_project_tasks_source_identity"
        ),
    )
    op.create_index(
        op.f("ix_project_tasks_ship_id"), "project_tasks", ["ship_id"], unique=False
    )
    op.create_table(
        "ship_systems",
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("system_code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(name) <> ''", name="ck_ship_systems_name"),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_ship_systems_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_ship_systems_source_system_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(system_code) <> ''", name="ck_ship_systems_system_code"
        ),
        sa.ForeignKeyConstraint(
            ["ship_id"], ["ships.id"], name="fk_ship_systems_ship_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_ship_systems_source_identity"
        ),
    )
    op.create_index(
        op.f("ix_ship_systems_ship_id"), "ship_systems", ["ship_id"], unique=False
    )
    op.create_table(
        "drawings",
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("system_id", sa.UUID(), nullable=True),
        sa.Column("drawing_no", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("revision", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(drawing_no) <> ''", name="ck_drawings_drawing_no"),
        sa.CheckConstraint("btrim(revision) <> ''", name="ck_drawings_revision"),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_drawings_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_drawings_source_system_non_blank"
        ),
        sa.CheckConstraint("btrim(title) <> ''", name="ck_drawings_title"),
        sa.CheckConstraint(
            "status IS NULL OR btrim(status) <> ''", name="ck_drawings_status"
        ),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], name="fk_drawings_ship_id"),
        sa.ForeignKeyConstraint(
            ["system_id"], ["ship_systems.id"], name="fk_drawings_system_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_drawings_source_identity"
        ),
    )
    op.create_index(op.f("ix_drawings_ship_id"), "drawings", ["ship_id"], unique=False)
    op.create_index(
        op.f("ix_drawings_system_id"), "drawings", ["system_id"], unique=False
    )
    op.create_table(
        "equipment",
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("system_id", sa.UUID(), nullable=True),
        sa.Column("drawing_id", sa.UUID(), nullable=True),
        sa.Column("equipment_code", sa.Text(), nullable=False),
        sa.Column("manufacturer", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "btrim(equipment_code) <> ''", name="ck_equipment_equipment_code"
        ),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_equipment_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_equipment_source_system_non_blank"
        ),
        sa.CheckConstraint(
            "manufacturer IS NULL OR btrim(manufacturer) <> ''",
            name="ck_equipment_manufacturer",
        ),
        sa.CheckConstraint(
            "model IS NULL OR btrim(model) <> ''", name="ck_equipment_model"
        ),
        sa.ForeignKeyConstraint(
            ["drawing_id"], ["drawings.id"], name="fk_equipment_drawing_id"
        ),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], name="fk_equipment_ship_id"),
        sa.ForeignKeyConstraint(
            ["system_id"], ["ship_systems.id"], name="fk_equipment_system_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_equipment_source_identity"
        ),
    )
    op.create_index(
        op.f("ix_equipment_drawing_id"), "equipment", ["drawing_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_ship_id"), "equipment", ["ship_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_system_id"), "equipment", ["system_id"], unique=False
    )
    op.create_table(
        "bom_items",
        sa.Column("drawing_id", sa.UUID(), nullable=True),
        sa.Column("equipment_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_bom_items_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''", name="ck_bom_items_source_system_non_blank"
        ),
        sa.CheckConstraint(
            "quantity > 0 AND quantity < 'Infinity'::numeric",
            name="ck_bom_items_quantity",
        ),
        sa.CheckConstraint(
            "drawing_id IS NOT NULL OR equipment_id IS NOT NULL",
            name="ck_bom_items_target",
        ),
        sa.ForeignKeyConstraint(
            ["drawing_id"], ["drawings.id"], name="fk_bom_items_drawing_id"
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.id"], name="fk_bom_items_equipment_id"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name="fk_bom_items_material_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_bom_items_source_identity"
        ),
    )
    op.create_index(
        op.f("ix_bom_items_drawing_id"), "bom_items", ["drawing_id"], unique=False
    )
    op.create_index(
        op.f("ix_bom_items_equipment_id"), "bom_items", ["equipment_id"], unique=False
    )
    op.create_index(
        op.f("ix_bom_items_material_id"), "bom_items", ["material_id"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("ship_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("equipment_id", sa.UUID(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("po_number", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=True),
        sa.Column("required_date", sa.Date(), nullable=True),
        sa.Column("promised_date", sa.Date(), nullable=True),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("criticality", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "btrim(po_number) <> ''", name="ck_purchase_orders_po_number"
        ),
        sa.CheckConstraint(
            "btrim(source_id) <> ''", name="ck_purchase_orders_source_id_non_blank"
        ),
        sa.CheckConstraint(
            "btrim(source_system) <> ''",
            name="ck_purchase_orders_source_system_non_blank",
        ),
        sa.CheckConstraint("btrim(status) <> ''", name="ck_purchase_orders_status"),
        sa.CheckConstraint(
            "criticality IS NULL OR btrim(criticality) <> ''",
            name="ck_purchase_orders_criticality",
        ),
        sa.CheckConstraint(
            "quantity IS NULL OR (quantity > 0 AND quantity < 'Infinity'::numeric)",
            name="ck_purchase_orders_quantity",
        ),
        sa.CheckConstraint(
            "material_id IS NOT NULL OR equipment_id IS NOT NULL",
            name="ck_purchase_orders_target",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.id"], name="fk_purchase_orders_equipment_id"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name="fk_purchase_orders_material_id"
        ),
        sa.ForeignKeyConstraint(
            ["ship_id"], ["ships.id"], name="fk_purchase_orders_ship_id"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name="fk_purchase_orders_supplier_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_purchase_orders_source_identity"
        ),
    )
    op.create_index(
        op.f("ix_purchase_orders_equipment_id"),
        "purchase_orders",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_material_id"),
        "purchase_orders",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_ship_id"), "purchase_orders", ["ship_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"),
        "purchase_orders",
        ["supplier_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_ship_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_material_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_equipment_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_bom_items_material_id"), table_name="bom_items")
    op.drop_index(op.f("ix_bom_items_equipment_id"), table_name="bom_items")
    op.drop_index(op.f("ix_bom_items_drawing_id"), table_name="bom_items")
    op.drop_table("bom_items")
    op.drop_index(op.f("ix_equipment_system_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_ship_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_drawing_id"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_drawings_system_id"), table_name="drawings")
    op.drop_index(op.f("ix_drawings_ship_id"), table_name="drawings")
    op.drop_table("drawings")
    op.drop_index(op.f("ix_ship_systems_ship_id"), table_name="ship_systems")
    op.drop_table("ship_systems")
    op.drop_index(op.f("ix_project_tasks_ship_id"), table_name="project_tasks")
    op.drop_table("project_tasks")
    op.drop_table("suppliers")
    op.drop_table("ships")
    op.drop_table("materials")
    # ### end Alembic commands ###
