"""create entity aliases

Revision ID: 20260818_0002
Revises: 20260817_0001
Create Date: 2026-08-18 16:10:42.038480
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260818_0002"
down_revision: str | Sequence[str] | None = "20260817_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("equipment_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(entity_type = 'supplier' AND supplier_id IS NOT NULL "
            "AND equipment_id IS NULL AND material_id IS NULL) OR "
            "(entity_type = 'equipment' AND supplier_id IS NULL "
            "AND equipment_id IS NOT NULL AND material_id IS NULL) OR "
            "(entity_type = 'material' AND supplier_id IS NULL "
            "AND equipment_id IS NULL AND material_id IS NOT NULL)",
            name="ck_entity_aliases_target",
        ),
        sa.CheckConstraint("btrim(alias) <> ''", name="ck_entity_aliases_alias"),
        sa.CheckConstraint(
            "btrim(normalized_alias) <> ''", name="ck_entity_aliases_normalized_alias"
        ),
        sa.CheckConstraint(
            "source_system IS NULL OR btrim(source_system) <> ''",
            name="ck_entity_aliases_source_system",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.id"], name="fk_entity_aliases_equipment_id"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name="fk_entity_aliases_material_id"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name="fk_entity_aliases_supplier_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_aliases_equipment_id"),
        "entity_aliases",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_aliases_material_id"),
        "entity_aliases",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_aliases_supplier_id"),
        "entity_aliases",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        "uq_entity_aliases_global_lookup",
        "entity_aliases",
        ["entity_type", "normalized_alias"],
        unique=True,
        postgresql_where=sa.text("source_system IS NULL"),
    )
    op.create_index(
        "uq_entity_aliases_source_lookup",
        "entity_aliases",
        ["entity_type", "source_system", "normalized_alias"],
        unique=True,
        postgresql_where=sa.text("source_system IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_entity_aliases_source_lookup",
        table_name="entity_aliases",
        postgresql_where=sa.text("source_system IS NOT NULL"),
    )
    op.drop_index(
        "uq_entity_aliases_global_lookup",
        table_name="entity_aliases",
        postgresql_where=sa.text("source_system IS NULL"),
    )
    op.drop_index(op.f("ix_entity_aliases_supplier_id"), table_name="entity_aliases")
    op.drop_index(op.f("ix_entity_aliases_material_id"), table_name="entity_aliases")
    op.drop_index(op.f("ix_entity_aliases_equipment_id"), table_name="entity_aliases")
    op.drop_table("entity_aliases")
    # ### end Alembic commands ###
